android.nonTransitiveRClass=true
kotlin.code.style=official
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
PALMPAY_CLONE_STORE_FILE=keystore/damjay_debug.keystore
PALMPAY_CLONE_STORE_PASSWORD=1b53591ced9ecd8d978eb6ef01b32498
PALMPAY_CLONE_KEY_ALIAS=photo-triage
PALMPAY_CLONE_KEY_PASSWORD=1b53591ced9ecd8d978eb6ef01b32498
