#!/usr/bin/env python3
"""gen_bindings.py -- emit AGP-style ViewBinding classes for the local precheck.

GhostHand's ECJ step needs the `*Binding` classes AGP would generate from the
layouts. They are mechanical: one public field per android:id, typed from the
element tag, plus inflate()/bind()/getRoot(). Merge-rooted layouts get the
two-arg inflate only, exactly like the real view binding compiler.

Usage: python3 tools/gen_bindings.py LAYOUT_DIR OUT_DIR
"""
import os
import sys
import xml.etree.ElementTree as ET

ANDROID = "{http://schemas.android.com/apk/res/android}"

TYPES = {
    "TextView": "android.widget.TextView",
    "EditText": "android.widget.EditText",
    "ImageView": "android.widget.ImageView",
    "ImageButton": "android.widget.ImageButton",
    "View": "android.view.View",
    "LinearLayout": "android.widget.LinearLayout",
    "FrameLayout": "android.widget.FrameLayout",
    "GridLayout": "android.widget.GridLayout",
    "RadioGroup": "android.widget.RadioGroup",
    "RadioButton": "android.widget.RadioButton",
    "ScrollView": "android.widget.ScrollView",
    "Space": "android.widget.Space",
    "ViewFlipper": "android.widget.ViewFlipper",
    "ListView": "android.widget.ListView",
    "NestedScrollView": "androidx.core.widget.NestedScrollView",
    "ConstraintLayout": "androidx.constraintlayout.widget.ConstraintLayout",
    "MaterialCardView": "com.google.android.material.card.MaterialCardView",
    "MaterialButton": "com.google.android.material.button.MaterialButton",
}


def camel(snake):
    parts = snake.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def pascal(snake):
    return "".join(p.capitalize() for p in snake.split("_"))


def field_type(tag, layout_attr):
    if tag == "include":
        name = os.path.basename(layout_attr or "").replace(".xml", "")
        return "damjay.palmpay.clone.databinding." + pascal(name) + "Binding"
    if "." in tag:
        return tag
    return TYPES.get(tag, "android.view.View")


def generate(layout_path):
    tree = ET.parse(layout_path)
    root = tree.getroot()
    merge = root.tag == "merge"
    fields = []
    seen = set()

    def walk(el):
        for child in el:
            ident = child.attrib.get(ANDROID + "id", "")
            if ident.startswith("@+id/"):
                raw = ident[5:]
                name = camel(raw)
                if name not in seen:
                    seen.add(name)
                    fields.append((name, field_type(
                        child.tag, child.attrib.get("layout")), raw))
            walk(child)

    walk(root)

    base = os.path.basename(layout_path).replace(".xml", "")
    cls = pascal(base) + "Binding"
    root_type = "android.view.View" if merge else field_type(
        root.tag, root.attrib.get("layout"))
    root_id = root.attrib.get(ANDROID + "id", "")
    if not merge and root_id.startswith("@+id/"):
        raw = root_id[5:]
        name = camel(raw)
        if name not in seen:
            seen.add(name)
            fields.insert(0, (name, root_type, raw))
    out = []
    out.append("package damjay.palmpay.clone.databinding;")
    out.append("")
    out.append("/** Generated by tools/gen_bindings.py for the local precheck. */")
    out.append("public final class %s {" % cls)
    out.append("    private final %s rootView;" % root_type)
    for name, ftype, rid in fields:
        out.append("    public final %s %s;" % (ftype, name))
    out.append("")
    out.append("    private %s(android.view.View root) {" % cls)
    out.append("        this.rootView = (%s) root;" % root_type)
    for name, ftype, rid in fields:
        if ftype.startswith("damjay.palmpay.clone.databinding."):
            out.append("        this.%s = %s.bind(root.findViewById(damjay.palmpay.clone.R.id.%s));"
                       % (name, ftype, rid))
        else:
            out.append("        this.%s = (%s) root.findViewById(damjay.palmpay.clone.R.id.%s);"
                       % (name, ftype, rid))
    out.append("    }")
    out.append("")
    out.append("    public %s getRoot() { return rootView; }" % root_type)
    out.append("")
    if merge:
        out.append("    public static %s inflate(android.view.LayoutInflater inflater, android.view.ViewGroup parent) {" % cls)
        out.append("        android.view.View root = inflater.inflate(damjay.palmpay.clone.R.layout.%s, parent, true);" % base)
        out.append("        return bind(parent);")
        out.append("    }")
    else:
        out.append("    public static %s inflate(android.view.LayoutInflater inflater) {" % cls)
        out.append("        return inflate(inflater, null, false);")
        out.append("    }")
        out.append("")
        out.append("    public static %s inflate(android.view.LayoutInflater inflater, android.view.ViewGroup parent, boolean attach) {" % cls)
        out.append("        android.view.View root = inflater.inflate(damjay.palmpay.clone.R.layout.%s, parent, attach);" % base)
        out.append("        return bind(root);")
        out.append("    }")
    out.append("")
    out.append("    public static %s bind(android.view.View root) {" % cls)
    out.append("        return new %s(root);" % cls)
    out.append("    }")
    out.append("}")
    return cls, "\n".join(out) + "\n"


def main():
    layout_dir, out_dir = sys.argv[1], sys.argv[2]
    os.makedirs(out_dir, exist_ok=True)
    count = 0
    for fname in sorted(os.listdir(layout_dir)):
        if not fname.endswith(".xml"):
            continue
        cls, text = generate(os.path.join(layout_dir, fname))
        with open(os.path.join(out_dir, cls + ".java"), "w") as handle:
            handle.write(text)
        count += 1
    print("    generated %d binding classes into %s" % (count, out_dir))


if __name__ == "__main__":
    main()
